name: Build
on:
  push:
    branches: [ main ]

jobs:
  lint-tests:
    uses: ./.github/workflows/lint-tests.yml

  bump-version:
    needs: lint-tests
    uses: ./.github/workflows/bump-version.yml
    secrets: inherit
    permissions:
      contents: write # required for bump-version to push a new tag
