name: Build
on:
  push:
    branches: [ main ]

jobs:
  lint-test:
    name: Tests and Lint
    uses: ./.github/workflows/lint-tests.yml

  bump-version:
    name: Bump Version
    needs: lint-test
    uses: ./.github/workflows/bump-version.yml
    secrets: inherit
    permissions:
      contents: write # required for bump-version to push a new tag
